# Site settings
name: Mojeed Oyedeji  
title: Mojeed Oyedeji | Full Stack Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: http://mojeedoyedeji.github.io
baseurl: '/'
email: mojeed.oyedeji@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:mojeed.oyedeji@gmail.com
  - title: twitter
    url: https://twitter.com/thisismojeed
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: github
    url: https://github.com/mojeedoyedeji
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
